export const Users = [
    {
      id:1,
      profilePicture: "person/p1.jpg",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "person/p2.jpg",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "person/p3.jpg",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "person/p4.jpg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "person/p5.jpg",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "person/p6.jpg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "person/p7.jpg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "person/p8.jpg",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "person/p9.jpg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "person/p10.jpg",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      name:"Mariya Rambo",
      desc: "Love For All, Hatred For None.",
      photo: "posts/1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      name:"lemar",
      photo: "posts/2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      name:"Anshu",
      desc: "Every moment is a fresh beginning.",
      photo: "posts/3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      name:"Roman Reign",
      photo: "posts/4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      name:"Neteliya",
      photo: "posts/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      name:"Flair",
      photo: "posts/6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      name:"Bechy",
      desc: "Never regret anything that made you smile.",
      photo: "posts/7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      name:"John cina",
      photo: "posts/8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      name:"Batista",
      desc: "Change the world by being yourself.",
      photo: "posts/9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      name:"John meto",
      photo: "posts/10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];